### ISSUE TITLE
Need to correctly parse strptime format string

### ISSUE THREAD

**Issue by bhealy-indeed** [pjknkda/flake8-datetimez#6]
Flagging strptime usages that use a static string mask that contains a %z

**Comment by pjknkda** [comment]
Could you give me an example?

If you mean the case that datetime format string is indirectly used in the argument, the linter cannot detect `%z` because it requires runtime checking.

```python
dt_s = '2021-12-09 14:49:16+0900'
dt_f = '%Y-%m-%d %H:%M:%S%z'
x = datetime.datetime.strptime(dt_s, dt_f)  # DTZ007 here beacuse the linter do not know the value inside of `dt_f`
```

**Comment by bhealy-indeed** [comment]
That's exactly the scenario, unfortunate that the linter can't see it. Thank you for the excellent tool.
